baseURL: "https://nmochea.github.io/writeups/"
languageCode: "en-us"
title: "Neilmark Ochea / 0xnmo"
theme: "PaperMod"
canonifyURLs: true

params:
  env: production
  title: Writeups
  description: "ExampleSite description"
  author: Me
  DateFormat: "November 17, 2025"
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  
  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "0xnmo"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false
    title: Neil Mark Ochea
    subtitle: |
      I just read manga, manhwa, and manhua. When I'm not reading, I'm busy exploring security vulnerabilities and hacking things."
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Neil Mark Ochea \U0001F577"
    Content: |
      I just love exploring security vulnerabilities and hacking things.
      
      Bug Bounty Researcher **@mobilehackinglab**

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/nmochea"
    - name: github
      url: "https://github.com/nmochea"
    - name: x
      url: "https://x.com/nmochea"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /writeups/posts/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /writeups/tags/
      weight: 20
    - identifier: pewpew
      name: Pewpew!
      url: https://mobilehackinglab.com
      weight: 30

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true 
    guessSyntax: true
    lineNos: false
    style: monokai
    safeMode: unsafe

frontmatter:
  format: yaml

goldmark:
  renderer:
    unsafe: true